# Generated by Django 5.1 on 2024-08-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_hashtag_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='hashteg',
            field=models.ManyToManyField(blank=True, to='journal.hashtag'),
        ),
    ]
